# Generated by Django 4.1.4 on 2022-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='', upload_to='staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
